import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Product, ProductPrice } from "@prisma/client";
import { Decimal } from "@prisma/client/runtime";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const products = api.product.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#eed991] to-[#ccf7f4] bg-fixed">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-800 sm:text-[5rem]">
            Your <span className="text-[hsl(280,100%,70%)]">personal</span>{" "}
            shopping assistant
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            {products.data ? (
              products.data.map((product) => (
                <Link
                  key={product.id}
                  className="flex flex-row gap-4 rounded-xl bg-white/10 p-4 text-slate-800 hover:bg-white/20"
                  href={`/product/${encodeURIComponent(product.id)}`}
                >
                  <div className="relative h-24 w-24 shrink-0 overflow-hidden">
                    {product.image ? (
                      <Image src={product.image} fill alt="product image" />
                    ) : (
                      <></>
                    )}
                  </div>
                  <div className="flex flex-col justify-center">
                    <h3 className="text-xl font-bold">{product.name}</h3>
                    <div className="text-lg font-bold text-slate-600">
                      ${product.prices[0]?.price || "-"}
                    </div>
                  </div>
                </Link>
              ))
            ) : (
              <>Loading</>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
